### ISSUE TITLE
Standardize the way fit! and predict methods take X matrix (features)

### ISSUE THREAD

**Issue by pebeto** [JuliaAI/DecisionTree.jl#220]
Some Julia packages uses columns as rows. This library forces the user to take data as completely tabular, as if it were a dataframe.

Example:
```julia
rfc = RandomForestClassifier()
x = rand(3, 100)
y = rand(0:1, 100)
DecisionTree.fit!(rfc, x, y) # it doesn't work because of BoundsError.
```

**Comment by ablaom** [comment]
@pebeto Thanks for your post.

> Some Julia packages uses columns as rows.

I guess you mean columns as *observations*?

Yes, the convention here is that each row of `x` represents a single observation. You are using the ScikitLearn.jl interface here (the `fit!` comes from that package) and that is the convention adopted there because that is the convention adopted in the python scikit-learn package. 

So this works just fine:

```julia
using DecisionTree

rfc = RandomForestClassifier()
x = rand(100,3) # 100 observations
y = rand(0:1, 100) # 100 observations
DecisionTree.fit!(rfc, x, y) # it doesn't work because of BoundsError.
```

The observation-as-rows convention is also the one adopted by the native API, and by the MLJ interface (which expects a table satisfying the Tables.jl API, such as a `DataFrame`, rather than a matrix).

By the way, this convention is the natural one for all tree models in Julia because tree models consume data one feature at a time, not one observation at a time as many other models do, and Julia arrays are column-major.

**Comment by pebeto** [comment]
When we create a matrix not by a tabular data source, you're getting a _columns * rows_ shape one where we can take rows as observations. My suggestion is something related to that, because there are libraries using this kind of "convention". So if there's some effort to change that from the original language behavior, there's no problem then. I thought it was something like "language feature".
