### ISSUE TITLE
RandomForestRegressor keep returning the same value

### ISSUE THREAD

**Issue by Applics** [JuliaAI/DecisionTree.jl#233]
Hello,

I want to implement the MissForest algorithm in julia which requires solving a lot of random forests.
However, I'm trying to do it with a very simple example. And, in this case, the regression gives the same output result every time regardless of the input given.

Is this normal behaviour? 

```julia
v1 = [11.0 21.0; 12.0 22.0; 14.0 24.0; 15.695 25.0; 17.0 27.0; 18.0 28.0; 19.0 29.0; 20.0 30.0]
v2 = [1.0, 2.0, 4.0, 5.0, 7.0, 8.0, 9.0, 10.0]

regr1 = RandomForestRegressor(n_trees=100)
fit!(regr1, v1, v2)
predict(regr1, [13.0, 23.0])
predict(regr1, [16.0, 26.0])
```

**Comment by Applics** [comment]
It might be useful to remove from the README.md that a RandomForestRegressor implementation is available, given the results xd.
also redirect to something that is actually working well (scikit-learn, ranger, etc)

**Comment by ablaom** [comment]
The issue is that your data has only 5 observations, but the default for the hyperparameter `min_samples_leaf` is 5. So every tree in the ensemble only has depth one (just a single decision for each tree). You actually do get different predictors, but you have to find just the right inputs to detect this. 

If you lower `min_samples_leaf` your trees have greater depth and you see different predictions more easily:

```julia
julia> regr1 = RandomForestRegressor(n_trees=100, min_samples_leaf=1)
RandomForestRegressor
n_trees:             100
n_subfeatures:       -1
partial_sampling:    0.7
max_depth:           -1
min_samples_leaf:    1
min_samples_split:   2
min_purity_increase: 0.0
ensemble:            nothing

fit!(regr1, v1, v2)

julia> predict(regr1, [13.0, 23.0])
3.33

julia> predict(regr1, [16.0, 26.0])
6.15

```

(Actual values will vary, because we are using the default RNG.)
